#!/usr/bin/env python
# encoding: utf-8

import sys
from lib.pxe_core import PXE


def run(ip_suffix, name):
    ip = '172.16.1.{0}'.format(ip_suffix)
    pxe = PXE(ip)
    m_type, suffix = name[:-3], name[-3:]
    if m_type == 'xenserver' or m_type == 'xcp':
        pxe.setup_xen_pxe(m_type + ip_suffix, m_type)
    elif m_type == 'centos':
        pxe.setup_centos_pxe(m_type + ip_suffix, m_type, suffix)
    elif m_type == 'esxi':
        pxe.setup_esxi_pxe(m_type + ip_suffix, m_type, suffix)
    pxe.generate_dhcp_http_pxe()


if __name__ == "__main__":
    run(sys.argv[1], sys.argv[2])
